# HitResult from UnrealEngine
# ref https://docs.unrealengine.com/5.1/en-US/API/Runtime/Engine/Engine/FHitResult/

bool blocking_hit
bool start_penetrating
string component_name
string actor_name
float32 distance
uint8 element_index
int32 face_index
string bone_name
int32 item
string my_bone_name
int32 my_item
float32 penetration_depth
string physics_material_name
float32 time
geometry_msgs/Vector3 impact_normal
geometry_msgs/Point impact_point
geometry_msgs/Vector3 normal
geometry_msgs/Point location
geometry_msgs/Point trace_start
geometry_msgs/Point trace_end

