string world_model                # World model name
string world_instance_name        # World instance unique name
geometry_msgs/Pose pose           # World instance initial pose
string json_parameters            # optional parameters, in json format
---
bool success
string status_message
